### ISSUE TITLE
Error when Calling a created CLI script 

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#243]
Call a created CLI:
`./bunnyCGAL_HiFlow3.msml.py -h`

returns

```
WARNING  Could not load imported repository /home/nschoch/HiFlow3_Project/MSML/msml/examples/BunnyExample/msml-repository.xml at .
WARNING  Could not load imported repository /home/nschoch/.config/msml/msml-repository.xml at .
INFO     READING alphabet...
INFO     Alphabet Paths:  
[Path(u'/home/nschoch/HiFlow3_Project/MSML/msml/share/alphabet')]
INFO     found 77 xml files in the alphabet search path
WARNING  _logical type Geometry requested, but does not exist WARNING  _logical type vector requested, but does not exist WARNING  _logical type vector.matID requested, but does not exist WARNING  _logical type PointSet requested, but does not exist WARNING  _logical type PointSet requested, but does not exist CRITICAL Slot pulse in parent surfacePressureOnMesh does not have a physical type defined. This can cause conversion errors.
WARNING  _logical type bool requested, but does not exist
ERROR    MiscPython Operators unavaiable because of ImportError: No  
module named scipy
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromParaCoeffs  
is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromParaCoeffs'
ERROR    msml.ext.misc_python.copy_file is not available  
(function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
ERROR     
msml.ext.misc_python.generateBeamDisplacementsFromSplineCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromSplineCoeffs'
ERROR    msml.ext.misc.measureMeshQuality is not available  
(function/attribute not found), got exception message ''module' object has no attribute 'measureMeshQuality'
ERROR    msml.ext.misc.calculateHausdorffDistance is not available  
(function/attribute not found), got exception message ''module' object has no attribute 'calculateHausdorffDistance'
INFO     Need convert value of <var input_vol_mesh : <Sort: <class  
'msml.sortdef.MSMLString'>, <class 'msml.sortdef.Mesh'>> = bunnyVolumeMeshCGAL.vtk>
INFO     Need convert value of <var input_surf_mesh : <Sort: <class  
'msml.sortdef.VTK'>, <class 'msml.sortdef.TriangularSurface'>> = Bunny6000Surface.vtk>
INFO     Need convert value of <var gen_1_ : <Sort: <type 'bool'>,  
None> = false>
INFO     Need convert value of <var gen_2_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 3>
INFO     Need convert value of <var gen_3_ : <Sort: <type 'bool'>,  
None> = false>
INFO     Need convert value of <var gen_4_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 0.02>
INFO     Need convert value of <var gen_5_ : <Sort: <type 'bool'>,  
None> = false>
INFO     Need convert value of <var gen_6_ : <Sort: <type 'bool'>,  
None> = false>
INFO     Need convert value of <var gen_7_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 20>
INFO     Need convert value of <var gen_8_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 0.006>
INFO     Need convert value of <var gen_9_ : <Sort: <type 'bool'>,  
None> = false>
INFO     Need convert value of <var gen_10_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 0.004>
INFO     Need convert value of <var gen_11_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.045 0.06>
INFO     Need convert value of <var gen_12_ : <Sort: <class  
'msml.sortdef.MSMLString'>, None> = points>
INFO     Need convert value of <var gen_13_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_14_ : <Sort: <class  
'msml.sortdef.MSMLString'>, None> = elements>
INFO     Need convert value of <var gen_15_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = -0.1 0.16 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_16_ : <Sort: <class  
'msml.sortdef.MSMLString'>, None> = points>
ERROR    Parameter name of Element mass is not specified in definition.
INFO     Need convert value of <var gen_17_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = 0.5 -0.06 -0.3>
INFO     Need convert value of <var gen_18_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 1.000>
INFO     Need convert value of <var gen_19_ : <Sort: <class  
'msml.sortdef.MSMLInt'>, None> = 4166>
INFO     Need convert value of <var gen_20_ : <Sort: <class  
'msml.sortdef.MSMLFloat'>, None> = 0.488>
INFO     Need convert value of <var gen_21_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = 0.01 0.0 -0.03>
INFO     Need convert value of <var gen_22_ : <Sort: <class  
'msml.sortdef.MSMLListF'>, None> = 0.0 0.02 0.0>
ERROR    some features are not supported by exporter
ERROR    -- msml_file: set(['object_element_displacement_supported',  
'output_supported', 'object_element_mass_supported', 'env_timeintegration_Newmark_supported',
'environment_multiple_simulation_steps_supported',
'constraints_supported', 'env_processingunit_CPU_supported',
'material_region_supported',
'env_preconditioner_SGAUSS_SEIDEL_supported',
'object_element_linearElasticMaterial_supported',
'sets_elements_supported', 'object_element_surfacePressure_supported',
'object_element_displacementConstraint_supported',
'amount_constraints_n', 'sets_surface_supported', 'environment_simulation_steps_supported', 'scene_objects_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported',
'env_linearsolver_CG_supported'])
ERROR    -- supported:  
frozenset(['object_element_displacement_supported',
'output_supported', 'object_element_mass_supported', 'env_processingunit_CPU_supported', 'constraints_supported', 'material_region_supported', 'env_linearsolver_iterativeCG_supported',
'env_preconditioner_None_supported',
'object_element_linearElasticMaterial_supported',
'scene_objects_supported',
'env_timeintegration_dynamicImplicitEuler_supported',
'sets_surface_supported', 'sets_elements_supported', 'environment_simulation_steps_supported',
'interbody_contact_simulation_supported',
'object_element_fixedConstraint_supported', 'sets_nodes_supported'])
ERROR    -- not matched: set(['env_linearsolver_CG_supported',  
'environment_multiple_simulation_steps_supported',
'amount_constraints_n', 'object_element_surfacePressure_supported',
'env_timeintegration_Newmark_supported',
'env_preconditioner_SGAUSS_SEIDEL_supported',
'object_element_displacementConstraint_supported'])
Traceback (most recent call last):
   File "./bunnyCGAL_HiFlow3.msml.py", line 27, in <module>
     main()
   File "./bunnyCGAL_HiFlow3.msml.py", line 23, in main
     executor_options = {}
   File
"/home/nschoch/HiFlow3_Project/MSML/msml/src/msml/api/clisupport.py",
line 170, in cli_app
     variables = get_arguments(mfile)
   File
"/home/nschoch/HiFlow3_Project/MSML/msml/src/msml/api/clisupport.py",
line 205, in get_arguments
     parser = clictk.build_argument_parser(exe)
   File
"/usr/local/lib/python2.7/dist-packages/clictk/argparseutil.py", line 26, in build_argument_parser
     for p in executable:
TypeError: iter() returned non-iterator of type 'tuple'
```

**Comment by markus-stoll** [comment]
You need to add `role="input"` for all vars that should be used as input.
Does this help?

**Comment by NicolaiSchoch** [comment]
Yes, but now there is another new error:

nschoch@numhpc0023:~/HiFlow3_Project/MSML/msml/examples/BunnyExample$ python bunnyCGAL_HiFlow3.msml.py
WARNING  Could not load imported repository /home/nschoch/HiFlow3_Project/MSML/msml/examples/BunnyExample/msml-repository.xml at .
WARNING  Could not load imported repository /home/nschoch/.config/msml/msml-repository.xml at .
INFO     READING alphabet...
INFO     Alphabet Paths: [Path(u'/home/nschoch/HiFlow3_Project/MSML/msml/share/alphabet')]
INFO     found 77 xml files in the alphabet search path
WARNING  _logical type Geometry requested, but does not exist
WARNING  _logical type vector requested, but does not exist
WARNING  _logical type vector.matID requested, but does not exist
WARNING  _logical type PointSet requested, but does not exist
WARNING  _logical type PointSet requested, but does not exist
CRITICAL Slot pulse in parent surfacePressureOnMesh does not have a physical type defined. This can cause conversion errors.
WARNING  _logical type bool requested, but does not exist
ERROR    MiscPython Operators unavaiable because of ImportError: No module named scipy
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromParaCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromParaCoeffs'
ERROR    msml.ext.misc_python.copy_file is not available (function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromSplineCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromSplineCoeffs'
ERROR    msml.ext.misc.measureMeshQuality is not available (function/attribute not found), got exception message ''module' object has no attribute 'measureMeshQuality'
ERROR    msml.ext.misc.calculateHausdorffDistance is not available (function/attribute not found), got exception message ''module' object has no attribute 'calculateHausdorffDistance'
INFO     Need convert value of <var input_vol_mesh : <Sort: <class 'msml.sortdef.MSMLString'>, <class 'msml.sortdef.Mesh'>> = bunnyVolumeMeshCGAL.vtk>
INFO     Need convert value of <var input_surf_mesh : <Sort: <class 'msml.sortdef.VTK'>, <class 'msml.sortdef.TriangularSurface'>> = Bunny6000Surface.vtk>
INFO     Need convert value of <var gen_1_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_2_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 3>
INFO     Need convert value of <var gen_3_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_4_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.02>
INFO     Need convert value of <var gen_5_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_6_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_7_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 20>
INFO     Need convert value of <var gen_8_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.006>
INFO     Need convert value of <var gen_9_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_10_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.004>
INFO     Need convert value of <var gen_11_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.045 0.06>
INFO     Need convert value of <var gen_12_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = points>
INFO     Need convert value of <var gen_13_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_14_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = elements>
INFO     Need convert value of <var gen_15_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.16 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_16_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = points>
ERROR    Parameter name of Element mass is not specified in definition.
INFO     Need convert value of <var gen_17_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.5 -0.06 -0.3>
INFO     Need convert value of <var gen_18_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 1.000>
INFO     Need convert value of <var gen_19_ : <Sort: <class 'msml.sortdef.MSMLInt'>, None> = 4166>
INFO     Need convert value of <var gen_20_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.488>
INFO     Need convert value of <var gen_21_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.01 0.0 -0.03>
INFO     Need convert value of <var gen_22_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.0 0.02 0.0>
ERROR    some features are not supported by exporter
ERROR    -- msml_file: set(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'env_timeintegration_Newmark_supported', 'environment_multiple_simulation_steps_supported', 'constraints_supported', 'env_processingunit_CPU_supported', 'material_region_supported', 'env_preconditioner_SGAUSS_SEIDEL_supported', 'object_element_linearElasticMaterial_supported', 'sets_elements_supported', 'object_element_surfacePressure_supported', 'object_element_displacementConstraint_supported', 'amount_constraints_n', 'sets_surface_supported', 'environment_simulation_steps_supported', 'scene_objects_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported', 'env_linearsolver_CG_supported'])
ERROR    -- supported: frozenset(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'env_processingunit_CPU_supported', 'constraints_supported', 'material_region_supported', 'env_linearsolver_iterativeCG_supported', 'env_preconditioner_None_supported', 'object_element_linearElasticMaterial_supported', 'scene_objects_supported', 'env_timeintegration_dynamicImplicitEuler_supported', 'sets_surface_supported', 'sets_elements_supported', 'environment_simulation_steps_supported', 'interbody_contact_simulation_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported'])
ERROR    -- not matched: set(['env_linearsolver_CG_supported', 'environment_multiple_simulation_steps_supported', 'amount_constraints_n', 'object_element_surfacePressure_supported', 'env_timeintegration_Newmark_supported', 'env_preconditioner_SGAUSS_SEIDEL_supported', 'object_element_displacementConstraint_supported'])
WARNING  Could not load imported repository /home/nschoch/HiFlow3_Project/MSML/msml/examples/BunnyExample/msml-repository.xml at .
WARNING  Could not load imported repository /home/nschoch/.config/msml/msml-repository.xml at .
INFO     READING alphabet...
INFO     Alphabet Paths: [Path(u'/home/nschoch/HiFlow3_Project/MSML/msml/share/alphabet')]
INFO     found 77 xml files in the alphabet search path
WARNING  _logical type Geometry requested, but does not exist
WARNING  _logical type vector requested, but does not exist
WARNING  _logical type vector.matID requested, but does not exist
WARNING  _logical type PointSet requested, but does not exist
WARNING  _logical type PointSet requested, but does not exist
CRITICAL Slot pulse in parent surfacePressureOnMesh does not have a physical type defined. This can cause conversion errors.
WARNING  _logical type bool requested, but does not exist
ERROR    MiscPython Operators unavaiable because of ImportError: No module named scipy
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromParaCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromParaCoeffs'
ERROR    msml.ext.misc_python.copy_file is not available (function/attribute not found), got exception message ''module' object has no attribute 'copy_file'
ERROR    msml.ext.misc_python.generateBeamDisplacementsFromSplineCoeffs is not available (function/attribute not found), got exception message ''module' object has no attribute 'generateBeamDisplacementsFromSplineCoeffs'
ERROR    msml.ext.misc.measureMeshQuality is not available (function/attribute not found), got exception message ''module' object has no attribute 'measureMeshQuality'
ERROR    msml.ext.misc.calculateHausdorffDistance is not available (function/attribute not found), got exception message ''module' object has no attribute 'calculateHausdorffDistance'
INFO     Need convert value of <var input_vol_mesh : <Sort: <class 'msml.sortdef.MSMLString'>, <class 'msml.sortdef.Mesh'>> = bunnyVolumeMeshCGAL.vtk>
INFO     Need convert value of <var input_surf_mesh : <Sort: <class 'msml.sortdef.VTK'>, <class 'msml.sortdef.TriangularSurface'>> = Bunny6000Surface.vtk>
INFO     Need convert value of <var gen_1_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_2_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 3>
INFO     Need convert value of <var gen_3_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_4_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.02>
INFO     Need convert value of <var gen_5_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_6_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_7_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 20>
INFO     Need convert value of <var gen_8_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.006>
INFO     Need convert value of <var gen_9_ : <Sort: <type 'bool'>, None> = false>
INFO     Need convert value of <var gen_10_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.004>
INFO     Need convert value of <var gen_11_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.045 0.06>
INFO     Need convert value of <var gen_12_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = points>
INFO     Need convert value of <var gen_13_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.03 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_14_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = elements>
INFO     Need convert value of <var gen_15_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = -0.1 0.16 -0.07 0.07 0.19 0.06>
INFO     Need convert value of <var gen_16_ : <Sort: <class 'msml.sortdef.MSMLString'>, None> = points>
ERROR    Parameter name of Element mass is not specified in definition.
INFO     Need convert value of <var gen_17_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.5 -0.06 -0.3>
INFO     Need convert value of <var gen_18_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 1.000>
INFO     Need convert value of <var gen_19_ : <Sort: <class 'msml.sortdef.MSMLInt'>, None> = 4166>
INFO     Need convert value of <var gen_20_ : <Sort: <class 'msml.sortdef.MSMLFloat'>, None> = 0.488>
INFO     Need convert value of <var gen_21_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.01 0.0 -0.03>
INFO     Need convert value of <var gen_22_ : <Sort: <class 'msml.sortdef.MSMLListF'>, None> = 0.0 0.02 0.0>
ERROR    some features are not supported by exporter
ERROR    -- msml_file: set(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'env_timeintegration_Newmark_supported', 'environment_multiple_simulation_steps_supported', 'constraints_supported', 'env_processingunit_CPU_supported', 'material_region_supported', 'env_preconditioner_SGAUSS_SEIDEL_supported', 'object_element_linearElasticMaterial_supported', 'sets_elements_supported', 'object_element_surfacePressure_supported', 'object_element_displacementConstraint_supported', 'amount_constraints_n', 'sets_surface_supported', 'environment_simulation_steps_supported', 'scene_objects_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported', 'env_linearsolver_CG_supported'])
ERROR    -- supported: frozenset(['object_element_displacement_supported', 'output_supported', 'object_element_mass_supported', 'env_processingunit_CPU_supported', 'constraints_supported', 'material_region_supported', 'env_linearsolver_iterativeCG_supported', 'env_preconditioner_None_supported', 'object_element_linearElasticMaterial_supported', 'scene_objects_supported', 'env_timeintegration_dynamicImplicitEuler_supported', 'sets_surface_supported', 'sets_elements_supported', 'environment_simulation_steps_supported', 'interbody_contact_simulation_supported', 'object_element_fixedConstraint_supported', 'sets_nodes_supported'])
ERROR    -- not matched: set(['env_linearsolver_CG_supported', 'environment_multiple_simulation_steps_supported', 'amount_constraints_n', 'object_element_surfacePressure_supported', 'env_timeintegration_Newmark_supported', 'env_preconditioner_SGAUSS_SEIDEL_supported', 'object_element_displacementConstraint_supported'])
Traceback (most recent call last):
  File "bunnyCGAL_HiFlow3.msml.py", line 27, in <module>
    main()
  File "bunnyCGAL_HiFlow3.msml.py", line 23, in main
    executor_options = {}
  File "/home/nschoch/HiFlow3_Project/MSML/msml/src/msml/api/clisupport.py", line 170, in cli_app
    variables = get_arguments(mfile)
  File "/home/nschoch/HiFlow3_Project/MSML/msml/src/msml/api/clisupport.py", line 226, in get_arguments
    value = os.path.abspath(value)
  File "/usr/lib/python2.7/posixpath.py", line 343, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 53, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
nschoch@numhpc0023:~/HiFlow3_Project/MSML/msml/examples/BunnyExample$

**Comment by NicolaiSchoch** [comment]
And executing:
nschoch@numhpc0023:~/HiFlow3_Project/MSML/msml/examples/BunnyExample$ ./bunnyCGAL_HiFlow3.msml.py -h

does not yield anything at all...

And executing
nschoch@numhpc0023:~/HiFlow3_Project/MSML/msml/examples/BunnyExample$ ./bunnyCGAL_HiFlow3.msml.py --xml
yields:
<executable><category>MSML</category><title>bunnyCGAL_HiFlow3.msml.xml</title><description>...</description><parameters advanced="false"><label>Offered Parameters</label><description>n/a</description><file><name>input_surf_mesh</name><longflag>input_surf_mesh</longflag><description> </description><label>input_surf_mesh</label><default>Bunny6000Surface.vtk</default><channel>input</channel></file></parameters></executable>

**Comment by NicolaiSchoch** [comment]
Okay, I guess it generally works now. :-)

The workflow should be:

1.) Test pipeline execution
`python ../../src/msml.py exec bunnyCGAL_HiFlow3.msml.xml -e hiflow3`

2.) Generate CLI script via
`python ../../src/msml.py cli bunnyCGAL_HiFlow3.msml.xml -e hiflow3`
This produces the file ``bunnyCGAL_HiFlow3.msml.py`

3.) Check out the CLI xml file via
`python bunnyCGAL_HiFlow3.msml.py --xml > bunnyCGAL_HiFlow3.msml.py.CLIinfo.xml`
in order to figure out how to use the variables as parameters for the CLI execution.
E.g. here, the "name" of the input variable is `input_surf_mesh`

4.) Execute CLI script via
`python bunnyCGAL_HiFlow3.msml.py --input_surf_mesh Bunny6000Surface.vtk`
possibly direct simulation output from console into `history.txt` file via
`python bunnyCGAL_HiFlow3.msml.py --input_surf_mesh Bunny6000Surface.vtk > history.txt`

---

What still doesn't work, is the `--help` or `-h` option... these don't produce anything... do they?
I cannot find any implementation of this functionality either... as opposed to the `--xml` option, which is in `src/msml/api/clisupport.py`.
However, they somehow should, as mentioned in areku's post on 11 Feb in https://github.com/CognitionGuidedSurgery/msml/issues/217.
Then, one could omit step 3) in the above description, and directly know how to handle step 4).

Any ideas how to get the `--help` work?

**Comment by NicolaiSchoch** [comment]
Am I right in thinking, that such produced CLI scripts are supposted to be feasible for handling in MITK CGS workbench (once the MITK support has created the corresponding plugin/interface), or is there anything further for us to be done from this stage on?

**Comment by wadoon** [comment]
See b015d971fe1b467e78877f2379ac437bfe30cfe7 
Fixed in branch `release_cand_1.0`

Additionally, update pyclictk: 

```
pip install -U pyclictk 
```

Current Version is 0.2.3

**Comment by NicolaiSchoch** [comment]
Ah, perfect! Thanks!! :)
Is there a reason, why this functionality is not in `experimental` branch yet?
Any objection to adding it there, too?

**Comment by wadoon** [comment]
This is a small patch. I have just checked out the default branch. 
You should be able to `cherry-pick` this commit. It is just a change of three lines.

**Comment by NicolaiSchoch** [comment]
Ah, yes, that works!

However, the `--help` still does not produce the output, which you pasted in issue 217:

```
(msml)➜  msml git:(experimental) ✗ python test.py --help
usage: test.py [-h] [--pr float] [--input_surf_mesh file.vtk] [--gen_1_ bool]
               [--ym float] [--gen_4_ vector.float] [--gen_3_ string]
               [--gen_2_ vector.float] [--gen_6_ float] [--input_vol_mesh str]
               [--gen_5_ string] [--xml]

optional arguments:
  -h, --help  show this help message and exit
  --xml       show cli xml
```

**Comment by markus-stoll** [comment]
cherry picked, the fix is now also available on experimental.

**Comment by markus-stoll** [comment]
Does everything work (except --help)? How is the MITK integration?
Make sure your needed data types are available in CTK (SFB S01 issue nr 167).

**Comment by NicolaiSchoch** [comment]
Yes, so far, everything seems to work fine; except for the "--help".

Alexander, do you remember, where and how you produced the output which you pasted in issue 217  (see also above)?
I cannot find it.
Maybe we could also cherry-pick this part in order to have it in the experimental branch?

About the MITK integration:
The data types should be fine; they fit to CTK as far as possible.
I talked to Andy about ways to test the MITK integration via MITK's CLI modules plugin, which is not yet in MITK CGS Workbench but will be in the soon-to-come next release.
We can still test it by using the standard MITK release 2015-05 and installing the plugin via CMake.
-- I did not yet do this.

However, along with Patrick I managed to use the CLI mitral valve preprocessing script for setting up a "cognitive app" prototype, which is now available in the SFB redmine/git (SFB B01 Cognitive Apps).
